### ISSUE TITLE
limit="-1" shows only one faq

### ISSUE THREAD

**Issue by NowellVanHoesen** [norcross/wordpress-faq-manager#18]
tried [faq limit="-1"]  and [faq limit=-1] on a page with the same results - 1 faq displayed

**Comment by norcross** [comment]
I'm guessing it's passing the number through `absint()` but I'll take a look

**Comment by NowellVanHoesen** [comment]
that would be it lib/data.php - line 134
using `intval()` works

**Comment by norcross** [comment]
you can put `all` as the variable and it should work, but I need to accommodate for the `-1`

**Comment by NowellVanHoesen** [comment]
`'posts_per_page'  => absint( $count ),` doesn't seem to like `all` for a limit value.
`[faq limit="all"]` displayed 5
`[faq all]` displayed 10

**Comment by norcross** [comment]
Just pushed an update that should resolve this. mind confirming?

**Comment by NowellVanHoesen** [comment]
confirmed
`[faq limit="all"]` and `[faq limit="-1"]` works as intended

thank you!

**Comment by norcross** [comment]
stellar!
