### ISSUE TITLE
ajax sorting isn't saving properly (refactor branch)

### ISSUE THREAD

**Issue by robincornett** [norcross/wordpress-faq-manager#22]
Installed the refactor branch on a new site, the master branch had never been used. Added questions and went to the sorting page. Drag and drop appears to work nicely and the success message appears after every move, but on the front end, the order doesn't change. If I refresh the sorting page, the questions appear in their original order.

Issue appears consistently in the new site (GoDaddy hosting, for which I am not responsible and I can only offer apologies) and locally. Working locally with script debug and wp debug both set to true, no PHP or console errors, but sorting doesn't "stick".

I do very minimal ajax so no suggestions to offer but since the success message shows, but the update doesn't happen, I'm guessing there is a disconnect in that method somewhere. Reverting to master did allow me to sort.

**Comment by norcross** [comment]
I'll see what's up. it very well could be just the logic in the query.

**Comment by norcross** [comment]
one question: is this display issue when using the shortcode, or normal display?

**Comment by robincornett** [comment]
The display issue is when using the shortcode, but it's also happening in the admin when I leave the sorting page and return to it, or refresh it. The shortcode in question is set to a specific topic with `-1` for the limit. I can explore more if you need.

**Comment by norcross** [comment]
that's all I needed to know. I'll see what's going on.

**Comment by norcross** [comment]
the latest commit should fix this. please pull down and verify @robincornett

**Comment by robincornett** [comment]
Verified, seems to be fixed. Thank you!
