### ISSUE TITLE
refactor branch: FAQ expand only accessible by filter?

### ISSUE THREAD

**Issue by robincornett** [norcross/wordpress-faq-manager#23]
I started with the refactor branch on a new site. Wanted the FAQ (using shortcode) to do the accordion/expand effect, but didn't see a setting or instructions to achieve this. Did some digging through the code and found the `wpfaq_display_content_expand` filter defined in the shortcodes.php file.

As I read it, seemed like the expand should be automatic (since default was set to true), but I followed the trail to the legacy.php file and then helper.php, and I think that since there is no legacy setting, the helper function is returning `false`, and since that's different from `empty`, the legacy filter is returning `false` for the expand setting as well.

I was able to override by adding a filter of my own to my theme, to return `wpfaq_display_content_expand` as true, but I'm wondering if you're intending for this to be accessible only by filter now, since there is no longer a settings page? I reverted to master and found the settings, and see that expand is not on by default, so this may be intentional, but I wanted to ask. Thanks!

**Comment by norcross** [comment]
that's correct. it isn't on by default, since I don't want to include any JS that people may not want (or be aware of existing). The legacy file is there to make sure if people have the setting already on, it'll respect it.
